import type { Destination } from "@/lib/types";

/**
 * Small curated set for MVP — expand without changing consumers.
 * Coordinates are approximate region centers for weather/swell placeholders.
 */
export const DESTINATIONS: Destination[] = [
  {
    id: "san-diego",
    slug: "san-diego",
    name: "San Diego",
    country: "USA",
    airportIata: "SAN",
    region: "Southern California",
    lat: 32.78,
    lon: -117.25,
    tagline: "Reef and beach breaks with a long intermediate-friendly season.",
  },
  {
    id: "santa-barbara",
    slug: "santa-barbara",
    name: "Santa Barbara",
    country: "USA",
    airportIata: "SBA",
    region: "Central California",
    lat: 34.42,
    lon: -119.7,
    tagline: "Channel swells and point waves when conditions line up.",
  },
  {
    id: "puerto-vallarta",
    slug: "puerto-vallarta",
    name: "Puerto Vallarta",
    country: "Mexico",
    airportIata: "PVR",
    region: "Jalisco",
    lat: 20.65,
    lon: -105.23,
    tagline: "Warm water and varied beach setups along Banderas Bay.",
  },
  {
    id: "liberia-costa-rica",
    slug: "liberia-costa-rica",
    name: "Guanacaste (Liberia)",
    country: "Costa Rica",
    airportIata: "LIR",
    region: "Guanacaste",
    lat: 10.6,
    lon: -85.45,
    tagline: "Consistent Pacific swell windows and sandy beach breaks.",
  },
  {
    id: "honolulu",
    slug: "honolulu",
    name: "Honolulu",
    country: "USA",
    airportIata: "HNL",
    region: "Oʻahu",
    lat: 21.32,
    lon: -157.85,
    tagline: "Reef passes with forgiving channels on smaller days.",
  },
  {
    id: "lisbon",
    slug: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    airportIata: "LIS",
    region: "Costa de Caparica / Ericeira orbit",
    lat: 38.72,
    lon: -9.14,
    tagline: "Atlantic power with plenty of sand-bottom options nearby.",
  },
  {
    id: "cape-town",
    slug: "cape-town",
    name: "Cape Town",
    country: "South Africa",
    airportIata: "CPT",
    region: "Western Cape",
    lat: -33.92,
    lon: 18.42,
    tagline: "Reef and beach setups with dramatic swell when the South Atlantic fires.",
  },
  {
    id: "bali",
    slug: "bali",
    name: "Bali (Denpasar)",
    country: "Indonesia",
    airportIata: "DPS",
    region: "Bukit / East Coast orbit",
    lat: -8.65,
    lon: 115.22,
    tagline: "Reef-lined coastlines — pick mellower dry-season windows as an intermediate.",
  },
  {
    id: "biarritz",
    slug: "biarritz",
    name: "Biarritz",
    country: "France",
    airportIata: "BIQ",
    region: "Pays Basque / Landes",
    lat: 43.47,
    lon: -1.56,
    tagline: "Beach breaks and mellow points when the Bay of Biscay delivers.",
  },
  {
    id: "gold-coast",
    slug: "gold-coast",
    name: "Gold Coast",
    country: "Australia",
    airportIata: "OOL",
    region: "Queensland",
    lat: -28.17,
    lon: 153.53,
    tagline: "Sand-bottom points and beachies with a long learning-friendly curve.",
  },
  {
    id: "oaxaca-coast",
    slug: "oaxaca-coast",
    name: "Oaxaca Coast",
    country: "Mexico",
    airportIata: "OAX",
    region: "Puerto Escondido orbit",
    lat: 15.87,
    lon: -97.07,
    tagline: "Powerful Pacific swells — seek softer shoulders away from the heaviest peaks.",
  },
  {
    id: "las-palmas",
    slug: "las-palmas",
    name: "Las Palmas (Gran Canaria)",
    country: "Spain",
    airportIata: "LPA",
    region: "Canary Islands",
    lat: 28.12,
    lon: -15.43,
    tagline: "Island trade-wind swells with varied reef and beach options.",
  },
  {
    id: "los-cabos",
    slug: "los-cabos",
    name: "Los Cabos",
    country: "Mexico",
    airportIata: "SJD",
    region: "Baja California Sur",
    lat: 23.05,
    lon: -109.7,
    tagline: "Desert coastline with coves and reefs when southern swells line up.",
  },
  {
    id: "nadi",
    slug: "nadi",
    name: "Nadi (Fiji)",
    country: "Fiji",
    airportIata: "NAN",
    region: "Mamanucas / Coral Coast orbit",
    lat: -17.75,
    lon: 177.44,
    tagline: "Reef passes that can soften on smaller swells — ideal for picky intermediates.",
  },
  {
    id: "lima",
    slug: "lima",
    name: "Lima",
    country: "Peru",
    airportIata: "LIM",
    region: "Costa Verde",
    lat: -12.05,
    lon: -77.04,
    tagline: "Consistent left-hand reef and beach setups along the urban coastline.",
  },
];

export function getDestinationBySlug(slug: string): Destination | undefined {
  return DESTINATIONS.find((d) => d.slug === slug);
}
